**1. Melakukan Import Library**

In [137]:
import pandas as pd

**2. Memuat Dataset Movie Sample**

In [138]:
df = pd.read_csv('/content/movie_sample_dataset.csv')
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

*Mengetahui dimensi (ukuran) DataFrame,jumlah baris dan kolom*

In [139]:
df.shape

(99, 13)

**3. Membersihkan Data**

a. Mengidentifikasi Missing Value

In [140]:
print("Jumlah baris & kolom sebelum cleaning:", df.shape)
print("Missing values sebelum cleaning:\n", df.isnull().sum())

#Hapus baris yang punya missing value di kolom manapun
df_clean = df.dropna().copy()

print("\nJumlah baris & kolom setelah cleaning:", df_clean.shape)
print("Missing values setelah cleaning:\n", df_clean.isnull().sum())

Jumlah baris & kolom sebelum cleaning: (99, 13)
Missing values sebelum cleaning:
 color                   11
director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

Jumlah baris & kolom setelah cleaning: (69, 13)
Missing values setelah cleaning:
 color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

In [141]:
# Tampilkan baris yang mengandung minimal 1 missing value
print("\nContoh baris dengan missing value")
print(df[df.isnull().any(axis=1)])
# Kolom yang mengandung NaN
print("\nKolom yang mengandung NaN:")
print(df.columns[df.isnull().any()])

Contoh baris dengan missing value
    color        director_name  duration        gross  \
5     NaN                  NaN       183  330249062.0
7   Color          Edward Hall       180          NaN
10    NaN           Tom Tykwer       172   27098580.0
12  Color  Christopher Spencer       170   59696176.0
15    NaN    Richard Linklater       165   25359200.0
18    NaN    Christopher Nolan       164  448130642.0
24  Color                  NaN       156  183635922.0
27  Color    Gnana Rajasekaran       153          NaN
32  Color                  NaN       150  182204440.0
33  Color           Mike Leigh       150    3958500.0
37  Color            Jay Oliva       148          NaN
41  Color                  NaN       147  407197282.0
56    NaN                  NaN       143          NaN
59  Color                  NaN       142  407999255.0
61  Color    Timur Bekmambetov       141          NaN
62  Color    Timur Bekmambetov       141          NaN
63  Color    Timur Bekmambetov       141          NaN
65    NaN         Oliver Stone       141   47307550.0
71  Color                  NaN       139  150832203.0
74    NaN      Terrence Malick       139   13303319.0
75  Color                  NaN       138  150117807.0
76    NaN      Robert Zemeckis       138   93749203.0
80    NaN        James Mangold       138  132550960.0
82  Color                  NaN       137   37304950.0
83    NaN        Walter Salles       137     717753.0
84  Color                  NaN       137  281666058.0
87    NaN      Seth MacFarlane       136   42615685.0
91  Color                  NaN       136   52474616.0
92  Color     Sadyk Sher-Niyaz       135          NaN
95  Color     Richard J. Lewis       134    7501404.0

                                    genres  \
5                  Action|Adventure|Sci-Fi
7                            Drama|Romance
10                            Drama|Sci-Fi
12                                     NaN
15                                   Drama
18                         Action|Thriller
24        Adventure|Drama|Thriller|Western
27                 Biography|Drama|History
32             Biography|Drama|History|War
33                 Biography|Drama|History
37  Action|Animation|Crime|Sci-Fi|Thriller
41                 Action|Adventure|Sci-Fi
56                   Drama|Horror|Thriller
59         Adventure|Drama|Sci-Fi|Thriller
61                 Adventure|Drama|History
62                 Adventure|Drama|History
63                 Adventure|Drama|History
65                    Crime|Drama|Thriller
71                Adventure|Mystery|Sci-Fi
74                           Drama|Fantasy
75                             Crime|Drama
76                          Drama|Thriller
80        Action|Adventure|Sci-Fi|Thriller
82                   Biography|Crime|Drama
83                         Adventure|Drama
84                        Adventure|Sci-Fi
87                          Comedy|Western
91                                   Drama
92          Action|Biography|Drama|History
95                            Comedy|Drama

                                movie_title  title_year language     country  \
5        Batman v Superman: Dawn of Justice         202  English         USA
7                                  Restless        2012  English          UK
10                              Cloud Atlas        2012  English     Germany
12                               Son of God        2014  English         USA
15                                  Boyhood        2014  English         USA
18                    The Dark Knight Rises        2012  English         USA
24                             The Revenant        2015  English         USA
27                                Ramanujan        2014  English       India
32                                  Lincoln        2012  English         USA
33                               Mr. Turner        2014  English          UK
37  Batman: The Dark Knight Returns, Part 2        2013  English         USA
41               Captain America: Civil War        2016  English         USA
56                               The Ridges        2011  English         USA
59                         The Hunger Games        2012  English         USA
61                                  Ben-Hur        2016  English         USA
62                                  Ben-Hur        2016  English         USA
63                                  Ben-Hur        2016  English         USA
65                                  Savages        2012  English         USA
71                                Divergent        2014  English         USA
74                         The Tree of Life        2011  English         USA
75                          American Hustle        2013  English         USA
76                                   Flight        2012  English         USA
80                            The Wolverine        2013  English         USA
82                                 J. Edgar        2011  English         USA
83                              On the Road        2012  English      France
84    The Hunger Games: Mockingjay - Part 2        2015  English         USA
87        A Million Ways to Die in the West        2014  English         USA
91          Wall Street: Money Never Sleeps        2010  English         USA
92                   Queen of the Mountains        2014  English  Kyrgyzstan
95                         Barney's Version        2010  English      Canada

         budget  imdb_score  \
5   250000000.0         6.9
7           NaN         7.2
10  102000000.0        -7.5
12   22000000.0         5.6
15    4000000.0         8.0
18  250000000.0         8.5
24  135000000.0         8.1
27          NaN         7.0
32   65000000.0         7.4
33          NaN         6.8
37    3500000.0         8.4
41  250000000.0         8.2
56      17350.0         3.0
59   78000000.0         7.3
61  100000000.0         6.1
62  100000000.0         6.0
63  100000000.0         6.1
65   45000000.0         6.5
71   85000000.0         6.7
74   32000000.0         6.7
75   40000000.0         7.3
76   31000000.0         7.3
80  120000000.0         6.7
82   35000000.0         6.6
83   25000000.0         6.1
84  160000000.0         6.6
87   40000000.0         6.1
91   70000000.0         6.3
92    1400000.0         8.7
95          NaN         7.3

                                               actors  movie_facebook_likes
5            Henry Cavill,Lauren Cohan,Alan D. Purwin                197000
7       Rufus Sewell,Hayley Atwell,Charlotte Rampling                   434
10               Tom Hanks,Jim Sturgess,Jim Broadbent                124000
12           Roma Downey,Amber Rose Revah,Darwin Shaw                 15000
15     Ellar Coltrane,Lorelei Linklater,Libby Villari                 92000
18      Tom Hardy,Christian Bale,Joseph Gordon-Levitt                164000
24             Leonardo DiCaprio,Tom Hardy,Lukas Haas                190000
27         Mani Bharathi,Michael Lieber,Kevin McGowan                    58
32     Joseph Gordon-Levitt,Hal Holbrook,Bruce McGill                 71000
33            Lesley Manville,Ruth Sheen,Karl Johnson                     0
37           Michael Emerson,Mark Valley,Grey Griffin                  5000
41   Robert Downey Jr.,Scarlett Johansson,Chris Evans                 72000
56      Robbie Barnes,Alana Kaniewski,Brandon Landers                    33
59  Jennifer Lawrence,Josh Hutcherson,Anthony Reyn...                140000
61           Morgan Freeman,Ayelet Zurer,Moises Arias                     0
62           Morgan Freeman,Ayelet Zurer,Moises Arias                     0
63           Morgan Freeman,Ayelet Zurer,Moises Arias                     0
65            Demián Bichir,Shea Whigham,Gary Stretch                 28000
71               Kate Winslet,Theo James,Mekhi Phifer                 49000
74                  Brad Pitt,Tye Sheridan,Fiona Shaw                 39000
75    Jennifer Lawrence,Christian Bale,Bradley Cooper                 63000
76  Denzel Washington,Bruce Greenwood,Nadine Velaz...                 64000
80            Hugh Jackman,Tao Okamoto,Rila Fukushima                 68000
82        Leonardo DiCaprio,Naomi Watts,Kaitlyn Dever                 16000
83      Kristen Stewart,Viggo Mortensen,Kirsten Dunst                 27000
84  Jennifer Lawrence,Philip Seymour Hoffman,Josh ...                 38000
87        Liam Neeson,Charlize Theron,Seth MacFarlane                 24000
91  Frank Langella,Austin Pendleton,John Buffalo M...                 13000
92  Elina Abai Kyzy,Aziz Muradillayev,Mirlan Abdul...                     0
95                   Mark Addy,Atom Egoyan,Paul Gross                     0

Kolom yang mengandung NaN:
Index(['color', 'director_name', 'gross', 'genres', 'budget'], dtype='object')

In [142]:
# Hapus baris yang punya NaN
df.dropna(inplace=True)
# Reset index setelah drop
df.reset_index(drop=True, inplace=True)
print("Setelah hapus nilai NaN:", df.shape)

Setelah hapus nilai NaN: (69, 13)

b. Normalisasi Teks

In [144]:
df.columns = df.columns.str.strip().str.title()
df['Color'] = df['Color'].astype(str).str.title()
df['Country'] = df['Country'].astype(str).str.title()
df['Language'] = df['Language'].astype(str).str.title()
df['Genres'] = df['Genres'].astype(str).str.title()
df['Director_Name'] = df['Director_Name'].astype(str).str.title()
df['Movie_Title'] = df['Movie_Title'].astype(str).str.strip().str.title()
df['Actors'] = df['Actors'].astype(str).str.title()

df

,Color,Director_Name,Duration,Gross,Genres,Movie_Title,Title_Year,Language,Country,Budget,Imdb_Score,Actors,Movie_Facebook_Likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf Of Wall Street,2013,English,Usa,100000000.0,8.2,"Leonardo Dicaprio,Matthew Mcconaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,Usa,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,Usa,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,Usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation Of Smaug,2013,English,Usa,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Color,Tony Gilroy,135,113165635.0,Action|Adventure|Thriller,The Bourne Legacy,2012,English,Usa,125000000.0,6.7,"Jeremy Renner,Scott Glenn,Stacy Keach",31000
65,Color,Steve Mcqueen,134,56667870.0,Biography|Drama|History,12 Years A Slave,2013,English,Usa,20000000.0,8.1,"Quvenzhané Wallis,Scoot Mcnairy,Taran Killam",83000
66,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,Usa,55000000.0,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
67,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,Usa,68000000.0,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
68,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,Usa,40000000.0,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

c. Menangani Nilai Tidak Standar

In [152]:
#Ganti string "N/A" dengan NaN
df.replace("N/A", np.nan, inplace=True)

#Hapus baris dengan NaN (setelah penggantian "N/A")
df = df.dropna()

#Hapus baris dengan nilai negatif di budget atau gross
df = df[(df['Budget'] >= 0) & (df['Gross'] >= 0)]
df

,Color,Director_Name,Duration,Gross,Movie_Title,Title_Year,Language,Country,Budget,Imdb_Score,...,Genre_Action,Genre_Romance,Genre_Drama,Genre_Musical,Genre_History,Genre_Comedy,Genre_Western,Genre_Sci-Fi,Genre_Crime,Genre_Mystery
0,Color,Martin Scorsese,240.0,116866727.0,The Wolf Of Wall Street,2013,English,Usa,100000000.0,8.2,...,0,0,1,0,0,1,0,0,1,0
1,Color,Shane Black,195.0,408992272.0,Iron Man 3,2013,English,Usa,200000000.0,7.2,...,1,0,0,0,0,0,0,1,0,0
2,Color,Quentin Tarantino,187.0,54116191.0,The Hateful Eight,2015,English,Usa,44000000.0,7.9,...,0,0,1,0,0,0,1,0,1,1
3,Color,Kenneth Lonergan,186.0,46495.0,Margaret,2011,English,Usa,14000000.0,6.5,...,0,0,1,0,0,0,0,0,0,0
4,Color,Peter Jackson,186.0,258355354.0,The Hobbit: The Desolation Of Smaug,2013,English,Usa,225000000.0,7.9,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Color,Tony Gilroy,135.0,113165635.0,The Bourne Legacy,2012,English,Usa,125000000.0,6.7,...,1,0,0,0,0,0,0,0,0,0
65,Color,Steve Mcqueen,134.0,56667870.0,12 Years A Slave,2013,English,Usa,20000000.0,8.1,...,0,0,1,0,1,0,0,0,0,0
66,Color,Paul Greengrass,134.0,107100855.0,Captain Phillips,2013,English,Usa,55000000.0,7.9,...,0,0,1,0,0,0,0,0,0,0
67,Color,David Ayer,134.0,85707116.0,Fury,2014,English,Usa,68000000.0,7.6,...,1,0,1,0,0,0,0,0,0,0
68,Color,Clint Eastwood,5.0,47034272.0,Jersey Boys,2014,English,Usa,40000000.0,6.9,...,0,0,1,1,0,0,0,0,0,0

In [153]:
#Mengatasi Nilai yang Negatif
df['Duration'] = df['Duration'].apply(lambda x: np.nan if x < 0 else x)
df['Imdb_Score'] = df['Imdb_Score'].apply(lambda x: np.nan if x < 0 else x)
df

,Color,Director_Name,Duration,Gross,Movie_Title,Title_Year,Language,Country,Budget,Imdb_Score,...,Genre_Action,Genre_Romance,Genre_Drama,Genre_Musical,Genre_History,Genre_Comedy,Genre_Western,Genre_Sci-Fi,Genre_Crime,Genre_Mystery
0,Color,Martin Scorsese,240.0,116866727.0,The Wolf Of Wall Street,2013,English,Usa,100000000.0,8.2,...,0,0,1,0,0,1,0,0,1,0
1,Color,Shane Black,195.0,408992272.0,Iron Man 3,2013,English,Usa,200000000.0,7.2,...,1,0,0,0,0,0,0,1,0,0
2,Color,Quentin Tarantino,187.0,54116191.0,The Hateful Eight,2015,English,Usa,44000000.0,7.9,...,0,0,1,0,0,0,1,0,1,1
3,Color,Kenneth Lonergan,186.0,46495.0,Margaret,2011,English,Usa,14000000.0,6.5,...,0,0,1,0,0,0,0,0,0,0
4,Color,Peter Jackson,186.0,258355354.0,The Hobbit: The Desolation Of Smaug,2013,English,Usa,225000000.0,7.9,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Color,Tony Gilroy,135.0,113165635.0,The Bourne Legacy,2012,English,Usa,125000000.0,6.7,...,1,0,0,0,0,0,0,0,0,0
65,Color,Steve Mcqueen,134.0,56667870.0,12 Years A Slave,2013,English,Usa,20000000.0,8.1,...,0,0,1,0,1,0,0,0,0,0
66,Color,Paul Greengrass,134.0,107100855.0,Captain Phillips,2013,English,Usa,55000000.0,7.9,...,0,0,1,0,0,0,0,0,0,0
67,Color,David Ayer,134.0,85707116.0,Fury,2014,English,Usa,68000000.0,7.6,...,1,0,1,0,0,0,0,0,0,0
68,Color,Clint Eastwood,5.0,47034272.0,Jersey Boys,2014,English,Usa,40000000.0,6.9,...,0,0,1,1,0,0,0,0,0,0

**4. Transformasi Data**

a. Memastikan kolom (gross, budget, duration, imdb_score) sudah bertipe numerik

In [154]:
# Pastikan kolom numerik dikonversi ke float
df['Gross'] = pd.to_numeric(df['Gross'], errors='coerce')
df['Budget'] = pd.to_numeric(df['Budget'], errors='coerce')
df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')
df['Imdb_Score'] = pd.to_numeric(df['Imdb_Score'], errors='coerce')

# Cek tipe data untuk memastikan
print(df.dtypes[['Gross', 'Budget', 'Duration', 'Imdb_Score']])

Gross         float64
Budget        float64
Duration      float64
Imdb_Score    float64
dtype: object

b. Memisahkan Kolom Genres Menjadi List

In [155]:
if 'Genres' in df.columns:
    df['Genres'] = df['Genres'].astype(str)
    df['Genres_List'] = df['Genres'].str.split('|')

    # ambil semua genre unik
    all_genres = set([g for sublist in df['Genres_List'] for g in sublist if g != 'nan'])

    # buat kolom Genre_<nama>
    for genre in all_genres:
        col_name = "Genre_" + genre.strip()
        df[col_name] = df['Genres_List'].apply(lambda x: 1 if genre in x else 0)

    # hapus kolom Genres asli
    df = df.drop(columns=['Genres','Genres_List'])
df

,Color,Director_Name,Duration,Gross,Movie_Title,Title_Year,Language,Country,Budget,Imdb_Score,...,Genre_Action,Genre_Romance,Genre_Drama,Genre_Musical,Genre_History,Genre_Comedy,Genre_Western,Genre_Sci-Fi,Genre_Crime,Genre_Mystery
0,Color,Martin Scorsese,240.0,116866727.0,The Wolf Of Wall Street,2013,English,Usa,100000000.0,8.2,...,0,0,1,0,0,1,0,0,1,0
1,Color,Shane Black,195.0,408992272.0,Iron Man 3,2013,English,Usa,200000000.0,7.2,...,1,0,0,0,0,0,0,1,0,0
2,Color,Quentin Tarantino,187.0,54116191.0,The Hateful Eight,2015,English,Usa,44000000.0,7.9,...,0,0,1,0,0,0,1,0,1,1
3,Color,Kenneth Lonergan,186.0,46495.0,Margaret,2011,English,Usa,14000000.0,6.5,...,0,0,1,0,0,0,0,0,0,0
4,Color,Peter Jackson,186.0,258355354.0,The Hobbit: The Desolation Of Smaug,2013,English,Usa,225000000.0,7.9,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,Color,Tony Gilroy,135.0,113165635.0,The Bourne Legacy,2012,English,Usa,125000000.0,6.7,...,1,0,0,0,0,0,0,0,0,0
65,Color,Steve Mcqueen,134.0,56667870.0,12 Years A Slave,2013,English,Usa,20000000.0,8.1,...,0,0,1,0,1,0,0,0,0,0
66,Color,Paul Greengrass,134.0,107100855.0,Captain Phillips,2013,English,Usa,55000000.0,7.9,...,0,0,1,0,0,0,0,0,0,0
67,Color,David Ayer,134.0,85707116.0,Fury,2014,English,Usa,68000000.0,7.6,...,1,0,1,0,0,0,0,0,0,0
68,Color,Clint Eastwood,5.0,47034272.0,Jersey Boys,2014,English,Usa,40000000.0,6.9,...,0,0,1,1,0,0,0,0,0,0

**5. Menyimpan Data Hasil Preprocessing**

In [156]:
df.to_csv("movie_dataset_normalized_final.csv", index=False)